### ISSUE TITLE
Function with JavaMailSender fails in auto configuration

### ISSUE THREAD

**Issue by trisberg** [projectriff/java-function-invoker#132]
Building a function that is using a JavaMailSender fails to start due to what looks like classpath issue. Source is here: https://github.com/doddatpivotal/notifier

I see this when running with debug:

```
   MailSenderAutoConfiguration:
      Did not match:
         - @ConditionalOnClass did not find required classes 'javax.mail.internet.MimeMessage', 'javax.activation.MimeType' (OnClassCondition)
```

Although the "missing" classes should be on the classpath since the following jars are there:
```
jar:file:/workspace/BOOT-INF/lib/activation-1.1.jar!/
jar:file:/workspace/BOOT-INF/lib/javax.mail-1.6.2.jar!/
```

The reported classpath:
`2019-08-08 19:29:58.725 DEBUG 1 --- [       Thread-3] .c.l.ClasspathLoggingApplicationListener : Application failed to start with classpath: [file:/workspace/BOOT-INF/classes/, jar:file:/workspace/BOOT-INF/lib/activation-1.1.jar!/, jar:file:/workspace/BOOT-INF/lib/gson-2.8.5.jar!/, jar:file:/workspace/BOOT-INF/lib/javax.annotation-api-1.3.2.jar!/, jar:file:/workspace/BOOT-INF/lib/javax.mail-1.6.2.jar!/, jar:file:/workspace/BOOT-INF/lib/jul-to-slf4j-1.7.25.jar!/, jar:file:/workspace/BOOT-INF/lib/log4j-api-2.10.0.jar!/, jar:file:/workspace/BOOT-INF/lib/log4j-to-slf4j-2.10.0.jar!/, jar:file:/workspace/BOOT-INF/lib/logback-classic-1.2.3.jar!/, jar:file:/workspace/BOOT-INF/lib/logback-core-1.2.3.jar!/, jar:file:/workspace/BOOT-INF/lib/lombok-1.16.22.jar!/, jar:file:/workspace/BOOT-INF/lib/slf4j-api-1.7.25.jar!/, jar:file:/workspace/BOOT-INF/lib/snakeyaml-1.19.jar!/, jar:file:/workspace/BOOT-INF/lib/spring-aop-5.0.10.RELEASE.jar!/, jar:file:/workspace/BOOT-INF/lib/spring-beans-5.0.10.RELEASE.jar!/, jar:file:/workspace/BOOT-INF/lib/spring-boot-2.0.6.RELEASE.jar!/, jar:file:/workspace/BOOT-INF/lib/spring-boot-autoconfigure-2.0.6.RELEASE.jar!/, jar:file:/workspace/BOOT-INF/lib/spring-boot-starter-2.0.6.RELEASE.jar!/, jar:file:/workspace/BOOT-INF/lib/spring-boot-starter-logging-2.0.6.RELEASE.jar!/, jar:file:/workspace/BOOT-INF/lib/spring-boot-starter-mail-2.0.6.RELEASE.jar!/, jar:file:/workspace/BOOT-INF/lib/spring-context-5.0.10.RELEASE.jar!/, jar:file:/workspace/BOOT-INF/lib/spring-context-support-5.0.10.RELEASE.jar!/, jar:file:/workspace/BOOT-INF/lib/spring-core-5.0.10.RELEASE.jar!/, jar:file:/workspace/BOOT-INF/lib/spring-expression-5.0.10.RELEASE.jar!/, jar:file:/workspace/BOOT-INF/lib/spring-jcl-5.0.10.RELEASE.jar!/]`

**Comment by dsyer** [comment]
The code you posted fails to build. I fixed it by adding a `spring.mail.host`. When that was working I ran it in riff and it seemed to work (processed a message and failed to send). So what did I miss?

**Comment by olegz** [comment]
I think this has never worked on java 11 since the original issue in SCF was specifically about `javax` stuff not working in Java 11. So perhaps the build pack or something got upgraded from 8 to 11 and . . .
Anyway, I do agree that this need to be looked at closer in SCF. Luckily we're doing some work to make class loading more consistent.

I'll post more updates next week

**Comment by olegz** [comment]
After spending some time, I actually can't see how the change in SCF mentioned [here](https://github.com/spring-cloud/spring-cloud-function/issues/391) is relevant, since with that change we're simply asking the current class-loader to load everything that is `javax.` (not just `javax.annotation`). So, is it possible to actually produce a stack trace so we can see who is trying to load what?

**Comment by olegz** [comment]
Actually after discussing it with Dave I am taking this back as the issue is easily reproducible now
